# Generated by Django 5.1.6 on 2025-03-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('protocol', models.CharField(max_length=10)),
                ('length', models.IntegerField()),
                ('latency', models.FloatField()),
                ('jitter', models.FloatField()),
                ('packet_loss', models.FloatField()),
                ('bandwidth', models.FloatField()),
                ('uplink_bandwidth', models.FloatField()),
                ('downlink_bandwidth', models.FloatField()),
                ('anomaly_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP')], max_length=10)),
                ('anomaly_type', models.CharField(choices=[('DDoS', 'DDoS'), ('Malware', 'Malware'), ('Intrusion', 'Intrusion')], max_length=50)),
            ],
        ),
    ]
